apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-flask
  namespace: myspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service-flask
  template:
    metadata:
      labels:
        app: ai-service-flask
    spec:
      containers:
        - name: ai-service-flask
          image: kubeflow-registry.default.svc.cluster.local:30000/ai-service-flask:0.1.2
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service-flask
  namespace: myspace
spec:
  type: ClusterIP
  selector:
    app: ai-service-flask
  ports:
  - port: 8051
    targetPort: 5000